### ISSUE TITLE
[DroneTelemetryFunctionApp query] handling race between read ReadDocument and UpsertDocument

### ISSUE THREAD

**Issue by kiranpradeep** [mspnp/serverless-reference-implementation#59]
If a second azure function gets invoked in parallel (threaded or instance), in StateChangeProcessor:: UpdateState [[1](https://github.com/mspnp/serverless-reference-implementation/blob/db1d66363369597cedfc565001e7aed4434b3cea/src/DroneTelemetry/DroneTelemetryFunctionApp/StateChangeProcessor.cs#L24)], we might race between `ReadDocumentAsync` and `UpsertDocumentAsync`. Should the implementation use AccessCondition with ETags?

**Comment by jocontr** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID [218979](https://dev.azure.com/ceapex/pnp/_workitems/edit/218979)

**Comment by kirpasingh** [comment]
@kiranpradeep Though your concerns about race condition are valid and may play an important role in certain scenarios (e.g. an order processing payment gateway) where stronger consistency is desirable, in this specific case we can live with eventual consistency i.e. last write wins since we're just merging the change of state in drone parameters and eventually state reported is correct(in case of race condition). So weighing in pros and cons between ETag based upsert (performance impact) and eventual consistency, the latter wins here. For further guidance on choosing consistency levels in CosmosDB, please visit [this link](https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels-choosing). Please feel free to provide your feedback!

**Comment by kiranpradeep** [comment]
@kirpasingh I felt even the eventual state is wrong. Assume, drone reports two states, first one from building A and second one from building B and loses battery, then _find my lost drone_ application using the last state, will report that drone was lost in building A. 
Maybe I did not get the intent correct which I assume is like: this reference implementation is not a production application and so an occasional wrong state is ok.
